replicas: 3
image: quay.io/pires/docker-elasticsearch-kubernetes:6.3.2
resources:
  cpu: 1000m
  memory: 25Gi
  storage: 25Gi
nodes:
- wn01
- wn02
- wn03
secrets:
  maprUserSecret: "mapr-provisioner-secrets"
  maprClusterSecret: "mapr-ticket-secret"
restServers: "172.30.203.1:8443"
cldbHosts: "172.30.203.1:7222,172.30.203.2:7222,172.30.203.3:7222"
cluster: "datapipeline-ecp.cluster.com"
replication: 1

