apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: grafanasc
  namespace: default
provisioner: com.mapr.csi-kdf
allowVolumeExpansion: true
reclaimPolicy: Delete
parameters:
    csiProvisionerSecretName: "{{ .Values.secrets.maprUserSecret }}"
    csiProvisionerSecretNamespace: "default"
    csiNodePublishSecretName: "{{ .Values.secrets.maprClusterSecret }}"
    csiNodePublishSecretNamespace: "default"
    restServers: "{{ .Values.restServers }}"
    cldbHosts: "{{ .Values.cldbHosts }}"
    cluster: "{{ .Values.cluster }}"
    securityType: "secure"
    namePrefix: "csi-grafana"
    mountPrefix: "/grafana"
    advisoryquota: "100M"
    trackMemory: "false"
    logLevel: "error"
    retainLogs: "false"
    replication: "{{ .Values.replication }}"

